name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run test 
      run: |
        python3 -m app.py

  deploy: 
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: deploy to production
        uses: appleboy/ssh-action@master

        with:
           host: ${{ secrets.SS_HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PRIVATE_KEY }}
           script:  |
            cd happysadsongs-frontend-2
            git pull origin main
            cd
            sudo systemctl restart gunicorn
            echo "Done"
            
